// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MsgDefine.Resolvers
{
    using System;
    using System.Buffers;
    using MessagePack;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(9)
            {
                { typeof(global::System.Collections.Generic.Dictionary<int, global::Models.Mail>), 0 },
                { typeof(global::Status), 1 },
                { typeof(global::MsgDefine.MessagePackage), 2 },
                { typeof(global::Models.Mail), 3 },
                { typeof(global::Models.Player), 4 },
                { typeof(global::MsgDefine.TestMsg.TestMsg1), 5 },
                { typeof(global::MsgDefine.TestMsg.TestMsg2), 6 },
                { typeof(global::MsgDefine.TestMsg.LoginReqMsg), 7 },
                { typeof(global::MsgDefine.TestMsg.RegisterReqMsg), 8 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.DictionaryFormatter<int, global::Models.Mail>();
                case 1: return new MsgDefine.Formatters.StatusFormatter();
                case 2: return new MsgDefine.Formatters.MsgDefine.MessagePackageFormatter();
                case 3: return new MsgDefine.Formatters.Models.MailFormatter();
                case 4: return new MsgDefine.Formatters.Models.PlayerFormatter();
                case 5: return new MsgDefine.Formatters.MsgDefine.TestMsg.TestMsg1Formatter();
                case 6: return new MsgDefine.Formatters.MsgDefine.TestMsg.TestMsg2Formatter();
                case 7: return new MsgDefine.Formatters.MsgDefine.TestMsg.LoginReqMsgFormatter();
                case 8: return new MsgDefine.Formatters.MsgDefine.TestMsg.RegisterReqMsgFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name


// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MsgDefine.Formatters
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class StatusFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Status>
    {
        public void Serialize(ref MessagePackWriter writer, global::Status value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((Int32)value);
        }

        public global::Status Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::Status)reader.ReadInt32();
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name



// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MsgDefine.Formatters.MsgDefine
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class MessagePackageFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MsgDefine.MessagePackage>
    {


        public void Serialize(ref MessagePackWriter writer, global::MsgDefine.MessagePackage value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            writer.Write(value.Id);
            formatterResolver.GetFormatterWithVerify<byte[]>().Serialize(ref writer, value.Data, options);
        }

        public global::MsgDefine.MessagePackage Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Id__ = default(int);
            var __Data__ = default(byte[]);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Data__ = formatterResolver.GetFormatterWithVerify<byte[]>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MsgDefine.MessagePackage();
            ____result.Id = __Id__;
            ____result.Data = __Data__;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MsgDefine.Formatters.Models
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class MailFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Models.Mail>
    {


        public void Serialize(ref MessagePackWriter writer, global::Models.Mail value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.Id);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Title, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Content, options);
        }

        public global::Models.Mail Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Id__ = default(int);
            var __Title__ = default(string);
            var __Content__ = default(string);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Title__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Content__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Models.Mail();
            ____result.Id = __Id__;
            ____result.Title = __Title__;
            ____result.Content = __Content__;
            return ____result;
        }
    }

    public sealed class PlayerFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Models.Player>
    {


        public void Serialize(ref MessagePackWriter writer, global::Models.Player value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Name, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, global::Models.Mail>>().Serialize(ref writer, value.Mails, options);
            formatterResolver.GetFormatterWithVerify<global::Status>().Serialize(ref writer, value.Status, options);
        }

        public global::Models.Player Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Name__ = default(string);
            var __Mails__ = default(global::System.Collections.Generic.Dictionary<int, global::Models.Mail>);
            var __Status__ = default(global::Status);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Name__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __Mails__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, global::Models.Mail>>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Status__ = formatterResolver.GetFormatterWithVerify<global::Status>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Models.Player();
            ____result.Name = __Name__;
            ____result.Mails = __Mails__;
            ____result.Status = __Status__;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MsgDefine.Formatters.MsgDefine.TestMsg
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class TestMsg1Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MsgDefine.TestMsg.TestMsg1>
    {


        public void Serialize(ref MessagePackWriter writer, global::MsgDefine.TestMsg.TestMsg1 value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(1);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Name, options);
        }

        public global::MsgDefine.TestMsg.TestMsg1 Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Name__ = default(string);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Name__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MsgDefine.TestMsg.TestMsg1();
            ____result.Name = __Name__;
            return ____result;
        }
    }

    public sealed class TestMsg2Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MsgDefine.TestMsg.TestMsg2>
    {


        public void Serialize(ref MessagePackWriter writer, global::MsgDefine.TestMsg.TestMsg2 value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(1);
            writer.Write(value.Age);
        }

        public global::MsgDefine.TestMsg.TestMsg2 Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Age__ = default(int);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Age__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MsgDefine.TestMsg.TestMsg2();
            ____result.Age = __Age__;
            return ____result;
        }
    }

    public sealed class LoginReqMsgFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MsgDefine.TestMsg.LoginReqMsg>
    {


        public void Serialize(ref MessagePackWriter writer, global::MsgDefine.TestMsg.LoginReqMsg value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Account, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Password, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Extra, options);
            formatterResolver.GetFormatterWithVerify<global::Models.Player>().Serialize(ref writer, value.Player, options);
        }

        public global::MsgDefine.TestMsg.LoginReqMsg Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Account__ = default(string);
            var __Password__ = default(string);
            var __Extra__ = default(string);
            var __Player__ = default(global::Models.Player);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Account__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __Password__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Extra__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __Player__ = formatterResolver.GetFormatterWithVerify<global::Models.Player>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MsgDefine.TestMsg.LoginReqMsg();
            ____result.Account = __Account__;
            ____result.Password = __Password__;
            ____result.Extra = __Extra__;
            ____result.Player = __Player__;
            return ____result;
        }
    }

    public sealed class RegisterReqMsgFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MsgDefine.TestMsg.RegisterReqMsg>
    {


        public void Serialize(ref MessagePackWriter writer, global::MsgDefine.TestMsg.RegisterReqMsg value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Phone, options);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Authcode, options);
        }

        public global::MsgDefine.TestMsg.RegisterReqMsg Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Phone__ = default(string);
            var __Authcode__ = default(string);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __Phone__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __Authcode__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MsgDefine.TestMsg.RegisterReqMsg();
            ____result.Phone = __Phone__;
            ____result.Authcode = __Authcode__;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

